/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PointsRouteImport } from './routes/points'
import { Route as LookRouteImport } from './routes/look'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRecommendLookRouteImport } from './routes/api/recommend-look'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const LookRoute = LookRouteImport.update({
  id: '/look',
  path: '/look',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendLookRoute = ApiRecommendLookRouteImport.update({
  id: '/api/recommend-look',
  path: '/api/recommend-look',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/look': typeof LookRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/api/recommend-look': typeof ApiRecommendLookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/look': typeof LookRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/api/recommend-look': typeof ApiRecommendLookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/appointments': typeof AppointmentsRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/look': typeof LookRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/api/recommend-look': typeof ApiRecommendLookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/look'
    | '/points'
    | '/profile'
    | '/reviews'
    | '/services'
    | '/api/recommend-look'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/look'
    | '/points'
    | '/profile'
    | '/reviews'
    | '/services'
    | '/api/recommend-look'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/appointments'
    | '/book'
    | '/contact'
    | '/look'
    | '/points'
    | '/profile'
    | '/reviews'
    | '/services'
    | '/api/recommend-look'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  LookRoute: typeof LookRoute
  PointsRoute: typeof PointsRoute
  ProfileRoute: typeof ProfileRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  ApiRecommendLookRoute: typeof ApiRecommendLookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/look': {
      id: '/look'
      path: '/look'
      fullPath: '/look'
      preLoaderRoute: typeof LookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommend-look': {
      id: '/api/recommend-look'
      path: '/api/recommend-look'
      fullPath: '/api/recommend-look'
      preLoaderRoute: typeof ApiRecommendLookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppointmentsRoute: AppointmentsRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  LookRoute: LookRoute,
  PointsRoute: PointsRoute,
  ProfileRoute: ProfileRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  ApiRecommendLookRoute: ApiRecommendLookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
